<?php

use yii\helpers\Html;
use yii\helpers\Url;
use humhub\widgets\Button;


/* @var $contentContainer humhub\components\View */

$bundle = \humhub\modules\power\assets\MapAsset::register($this);

$this->registerJsConfig('weather', [
    'text' => [
        'confirm.delete' => 'Do you really want to delete this {number} item(s) with all subcontent?',
        'confirm.delete.header' =>  '<strong>Confirm</strong> delete file',
        'confirm.delete.confirmText' =>  'Delete'
    ],
    'showUrlModal' => [
        'head' => '<strong>File</strong> url',
        'headFile' => '<strong>File</strong> download url',
        'headFolder' =>'<strong>Folder</strong> url',
        'info' => 'Copy to clipboard',
        'buttonClose' => 'Close',
    ]
]);

$authClient = Yii::$app->user->getCurrentAuthClient();
if($authClient == null){
    $authClient = Yii::$app->authClientCollection->getClients()["globus"];
}
$accessToken = $authClient->getAccessToken();

$token = array();
$token["access_token"] = $accessToken->getToken();
$token["other_tokens"] = $accessToken->getParam('other_tokens');
$otherTokens = \yii\helpers\Json::encode($token);

$username = Yii::$app->user->identity->username;

$guid = Yii::$app->user->getGuid();

$space = $contentContainer;
$className = $space::className();

if(strcmp($className,'humhub\modules\space\models\Space') == 0){
    $sguid = $space->guid;
    $spaceName = strtolower($space->getDisplayName());
    $spaceName = str_replace(' ', 's', $spaceName);
    $spaceName = str_replace('-', 's', $spaceName);
    $spaceName = preg_replace('/[^A-Za-z0-9\-]/', 's', $spaceName);
    $username = $authClient->getUserAttributes()['preferred_username'];
    $username_pieces = explode("@",$username);
    $link = ' https://labs.scio.systems/secureMap?usr='.$username_pieces[0].'&guid='.$spaceName;
}else{
    $username = $authClient->getUserAttributes()['preferred_username'];
    $username_pieces = explode("@",$username);
    $sguid = $guid;
    $link = ' https://labs.scio.systems/secureMap?usr='.$username_pieces[0].'&guid='.$guid;
}



//$link = 'https://labs.scio.systems:8000/user/'.$username_pieces[0].'/lab?guid='.$guid;



?>

<?= Html::beginForm("", "POST", ['data-target' => '#globalModal', 'id' => 'map-form']); ?>
<div id="map-container" class="panel panel-default map-content">

    <div class="panel-body">

        <div class="panel-heading">

            <strong>Geospatial Exploration</strong>

            <p>
                Explore crop production estimates generated by the Spatial Production Allocation Model (SPAM)
                for 2000, 2005, and 2010; collection sites from the Genesys database for the approximately
                4 million accessions stored in genebanks worldwide;
                and several global climate model (GCM) projections for the four representative concentrations
                pathways (RCPs) from the 2030s through the 2080s.
            </p>

        </div>

        <div align="center">
            <?=
            Html::a('Connect to Geospatial Exploration', $link, ['target'=>'_blank','class'=>'btn btn-info btn-primary']); ?>
        </div>



    </div>
</div>
<?= Html::endForm(); ?>




